In [2]:
! pip install numpy

In [3]:
import numpy as np
print(np.__version__)

2.4.2


In [9]:
shop_sales = [120,150,180,200,170]
shop_array= np.array(shop_sales)
print(shop_array)
total = np.sum(shop_array)
print(f"Total sales:{total}")
Average= np.mean(shop_array)
print(f"Average sales:{Average}")

[120 150 180 200 170]
Total sales:820
Average sales:164.0


In [12]:
student_marks = [45,67,89,76,55,90]
marks = np.array(student_marks)
print(marks)
highest = np.max(marks)
lowest = np.min(marks)
Avg = np.mean(marks)

print(f'The highest marks is : {highest}')
print(f'The lowest marks is : {lowest}')
print(f'The Average marks is : {Avg:.2f}')

[45 67 89 76 55 90]
The highest marks is : 90
The lowest marks is : 45
The Average marks is : 70.33


In [24]:
distance = [2,3,4,5,3,4,6]
distance2 = np.array(distance)
print(distance2)
Total_Distance= np.sum(distance2)
Greater_than_4 = distance2[distance2>4]
formatted_distances = " and ".join([f"{val} km" for val in Greater_than_4])
print(f'The total distance covered in 7 days is {Total_Distance} km')
print(f'The distance covered greater than 4 km in 7 days is {formatted_distances}')

[2 3 4 5 3 4 6]
The total distance covered in 7 days is 27 km
The distance covered greater than 4 km in 7 days is 5 km and 6 km


In [37]:
prices_of_items = [[10,20,30],
                   [15,25,35]]
prices_of_shops = np.array(prices_of_items)
print(prices_of_shops)
# by using slicing 
print(f'The 3rd item of the 2nd shop is {prices_of_shops[1,2]}')

Total_price = np.sum(prices_of_shops)
print(f'The total price of both shop item is {Total_price}')

[[10 20 30]
 [15 25 35]]
The 3rd item of the 2nd shop is 35
The total price of both shop item is 135


In [42]:
score = [10,20,30,40]
score1 = np.array(score)
print(score1)
updated_score = score1 + 10
print(f"Updated scores are {updated_score}") 

[10 20 30 40]
Updated scores are [20 30 40 50]
