# Learning NumPy Day-2

In [1]:
! pip install numpy

In [2]:
import numpy as np
np.__version__

'2.4.2'

# Broadcasting

In [3]:
arr = np.array([1,2,3])
arr.shape

arr2 = np.array([5,6,7])
arr.shape    

(3,)

In [4]:
print(arr + arr2)

[ 6  8 10]


In [5]:
# Different shapes

In [6]:
array1 = np.array([1,2,3]) 
array1.shape

(3,)

In [7]:
array2 = np.array([5])
array2.shape

(1,)

In [8]:
print(array1+array2)

[6 7 8]


In [9]:
array1 = np.array([1,2,3]) 
array1.shape

(3,)

In [10]:
array2= np.array([[4],[5]])
array2.shape

(2, 1)

In [11]:
print(array1+array2) 

[[5 6 7]
 [6 7 8]]


In [12]:
print(array1*array2)

[[ 4  8 12]
 [ 5 10 15]]


In [13]:
x = np.random.random((5, 1, 4, 1, 8, 2, 1, 9, 1, 10))
y = np.random.random((1, 3, 1, 7, 8, 1, 6, 9, 1, 10))
print((x+y).shape)

(5, 3, 4, 7, 8, 2, 6, 9, 1, 10)


# Slicing and indexing

In [14]:
a = np.array([[5, 1, 4],
            [1,9, 8],
            [9, 1, 10]])

print(a[0:2])     # indexing rows

[[5 1 4]
 [1 9 8]]


In [15]:
print(a[(0,1)]) 

1


In [16]:
print(a[:,1])     # indexing columns

[1 9 1]


In [17]:
# Indexing the third column 2rd number

In [18]:
print(a[:,1][1])

9


In [19]:
print(a[:,1,np.newaxis]) # axising middle terms   

[[1]
 [9]
 [1]]


In [20]:
# Indexing first and last number

In [21]:
print(a[[0,2],[0,-1]])

[ 5 10]


In [22]:
# indexing 4 9 9

In [23]:
print(a[[0,1,2],[-1,1,0]])

[4 9 9]


In [24]:
# For getting 1st and last column using boolean values
print(a[[True,False,True]])

[[ 5  1  4]
 [ 9  1 10]]


In [25]:
# For indexing 1st and last column but except the mid value
print(a[:,[True,False,True]])

[[ 5  4]
 [ 1  8]
 [ 9 10]]


In [26]:
# Indexing numbers in an array using boolean values [4 8 1]

In [27]:
print(a[[[False,False,True],[False,False,True],[False,True,False]]])

[4 8 1]


In [28]:
# Sorting values

In [29]:
a = np.array([[[3,1,8],
              [6,2,1],
              [3,6,9]]])
print(a)

[[[3 1 8]
  [6 2 1]
  [3 6 9]]]


In [30]:
print(np.sort(a))

[[[1 3 8]
  [1 2 6]
  [3 6 9]]]


In [31]:
array= np.array([[[9,8,7],
                  [6,5,4],
                  [3,2,1]]])
print(np.sort(array)) # axis = 0 By default sort column wise

[[[7 8 9]
  [4 5 6]
  [1 2 3]]]


In [32]:
print(np.sort(array,axis = 1))  # sort row wise

[[[3 2 1]
  [6 5 4]
  [9 8 7]]]


In [33]:
print(np.sort(np.sort(array,axis = 0), axis = 1))

[[[3 2 1]
  [6 5 4]
  [9 8 7]]]


In [34]:
# for getting the array in corret series 

In [35]:
print(np.sort(array.flatten()).reshape(array.shape))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [36]:
outputs = np.array([0.05,0.01,0.87,0.02,0.01,0,0.01])
print(np.argmax(outputs))      # Maximum number

2


In [37]:
print(np.argmin(outputs)) # minimum number

5


In [38]:
print(np.nonzero(outputs))

(array([0, 1, 2, 3, 4, 6]),)


In [39]:
print(np.where(outputs>0.01,outputs,0))

[0.05 0.   0.87 0.02 0.   0.   0.  ]


# Iterations

In [40]:
a = np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [41]:
for row in a:
    for element in row:
        print(element) # series

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [42]:
for element in np.nditer(a):
    print(element,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [43]:
with np.nditer(a, op_flags = ['readwrite']) as it:
    for element in it:
        element[...]= element*2

print(a)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


# Masking

In [44]:
import numpy.ma as ma

arr= np.array([1,2,3,np.nan,4,np.inf])
masked_arr= ma.masked_array(arr,mask = [0,0,0,1,0,1])
print(masked_arr.mean())
print(masked_arr)

2.5
[1.0 2.0 3.0 -- 4.0 --]


In [48]:
arr = np.array([[1,2,3],
               [4,5,6]])
masked_arr = ma.masked_array(arr,mask = [[0,1,0],[0,1,0]])
print(masked_arr.mean())
print(masked_arr )

3.5
[[1 -- 3]
 [4 -- 6]]


In [47]:
print(ma.getmask(masked_arr))

[[False  True False]
 [False  True False]]


In [53]:
print(ma.masked_greater(arr,value=4))

[[1 2 3]
 [4 -- --]]


In [54]:
print(ma.masked_inside(arr,v1 = 2,v2 = 4))

[[1 -- --]
 [-- 5 6]]


In [55]:
print(ma.masked_outside(arr,v1 = 2,v2 = 5))

[[-- 2 3]
 [4 5 --]]


In [56]:
print(ma.masked_where(arr % 2 == 0 ,arr))

[[1 -- 3]
 [-- 5 --]]


In [59]:
print(ma.masked_where(arr % 2 != 0,arr))

[[-- 2 --]
 [4 -- 6]]


In [60]:
print(ma.masked_invalid(arr))

[[1 2 3]
 [4 5 6]]


In [62]:
arr= np.array([1,2,3,np.nan,4,np.inf])
print(ma.masked_invalid(arr))

[1.0 2.0 3.0 -- 4.0 --]


# Views and copies

In [65]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr[0:5]
print(new_arr)

[1 2 3 4 5]


In [66]:
new_arr[1] = 100
print(new_arr)

[  1 100   3   4   5]


In [67]:
print(arr)

[  1 100   3   4   5   6]


In [82]:
arr = np.array([[1,2,3],
               [4,5,6],
               [8,9,0]])
new_arr= arr.copy()

In [80]:
new_arr = arr[[0,1]]
new_arr[0][1]= 12
print(new_arr)

[[ 1 12  3]
 [ 4  5  6]]


In [81]:
print(arr)    # not updated

[[1 2 3]
 [4 5 6]
 [8 9 0]]


In [83]:
arr = np.array([[1,2,3],
               [4,5,6],
               [8,9,0]])
print(arr.base)
print(arr.copy().base)

None
None


In [85]:
print(arr.copy()[0:2].base)

[[1 2 3]
 [4 5 6]
 [8 9 0]]


# Vectorisation

In [89]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [92]:
def square_if_even(x):
    if x % 2 == 0:
        return x**2
    else:
        return x
vec_arr_square_if_even = np.vectorize(square_if_even)
print(vec_arr_square_if_even(arr))

[[ 1  4  3]
 [16  5 36]
 [ 7 64  9]]


In [94]:
a = np.array([[1,2],
             [3,4]])
b = np.array([[0,5],
             [10,15]])
c = np.array([[None,None],
              [None,None]])

c[0,0] = a[0, 0] * b[0, 0] + a[0, 1] * b[1, 0]
c[0,1] = a[0, 0] * b[0, 1] + a[0, 1] * b[1, 1]
c[1,0] = a[1, 0] * b[0, 0] + a[1, 1] * b[1, 0]
c[1,1 ]= a[1, 0] * b[0, 1] + a[1, 1] * b[1, 1]

In [95]:
print(c)

[[np.int64(20) np.int64(35)]
 [np.int64(40) np.int64(75)]]


In [96]:
print(np.matmul(a,b))

[[20 35]
 [40 75]]


In [97]:
print(a @ b)

[[20 35]
 [40 75]]


# Custom Data Types

In [99]:
arr = np.array([1,2,3])
print(arr.dtype)

int64


In [100]:
arr = np.array([1,2.9,3.0])
print(arr.dtype)

float64


In [101]:
arr = np.array([1,2.9,3.0,'hello','Star'])
print(arr.dtype)

<U32


In [102]:
arr = np.array([1,2.9,3.0,'hello','Star',{'key':'value'}])
print(arr.dtype)

object


In [4]:
dt = np.dtype(np.int32)
print(dt.name)

int32


In [6]:
print(dt.type)

<class 'numpy.int32'>


In [7]:
print(dt.byteorder)

=


In [14]:
print(dt.itemsize)

4


# Thanks for visiting